name: floss_inventory
version: 0.0.0
description: List of all the projects that I'm currently maintaining and under my account (for my use).

environment:
  sdk: '>=2.19.5'

dependencies:
  yaml: ^3.1.1
